-- generated by postgres4all; do not edit
-- document_store: MongoDB -> jsonb + GIN index
CREATE TABLE products (
    id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name       text  NOT NULL,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX products_attrs_gin ON products USING gin (attributes jsonb_path_ops);

INSERT INTO products (name, attributes) VALUES
    ('Mechanical Keyboard', '{"brand":"Keychron","switch":"brown","wireless":true,"tags":["typing","gaming"]}'),
    ('USB-C Hub',           '{"brand":"Anker","ports":7,"wireless":false}');

