#!/usr/bin/env bash
set -euo pipefail

CAPS=(document_store job_queue search vector gis timeseries dashboards api auth)

die() { echo "ERROR: $*" >&2; exit 1; }

DRY_RUN=0
CONFIG=""
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --*) die "unknown option: $arg" ;;
    *) CONFIG="$arg" ;;
  esac
done
[ -n "$CONFIG" ] || CONFIG="config.json"

# --- preflight ---
for tool in jq openssl; do
  command -v "$tool" >/dev/null 2>&1 || die "missing required tool: $tool"
done
if [ "$DRY_RUN" -eq 0 ]; then
  command -v docker >/dev/null 2>&1 || die "missing required tool: docker"
  docker compose version >/dev/null 2>&1 || die "missing required tool: docker compose"
fi

# --- read config ---
[ -f "$CONFIG" ] || die "config file not found: $CONFIG"
jq -e . "$CONFIG" >/dev/null 2>&1 || die "invalid JSON in $CONFIG"

cap() { # cap <name> -> "1" if enabled else "0"
  jq -r --arg k "$1" '.capabilities[$k] // false | if . then 1 else 0 end' "$CONFIG"
}
declare -A EN
for c in "${CAPS[@]}"; do EN[$c]=$(cap "$c"); done

# --- validate ---
any=0; for c in "${CAPS[@]}"; do [ "${EN[$c]}" = 1 ] && any=1; done
[ "$any" = 1 ] || die "no capabilities enabled in $CONFIG"

if [ "${EN[auth]}" = 1 ] && [ "${EN[api]}" = 0 ]; then
  die "capability 'auth' requires 'api'. Enable \"api\": true in $CONFIG."
fi

if [ "${EN[dashboards]}" = 1 ] && [ "${EN[timeseries]}" = 0 ]; then
  die "capability 'dashboards' requires 'timeseries'. Enable \"timeseries\": true in $CONFIG."
fi

echo "config OK: $(for c in "${CAPS[@]}"; do [ "${EN[$c]}" = 1 ] && printf '%s ' "$c"; done)"

PG_MAJOR=17
POSTGIS_VERSION=3.5
PG_GRAPHQL_VERSION=1.5.11

cd "$(dirname "$0")"  # anchor build/ output next to the script; config already read above
rm -rf build
mkdir -p build/init

# --- Dockerfile ---
{
  if [ "${EN[gis]}" = 1 ]; then
    echo "FROM postgis/postgis:${PG_MAJOR}-${POSTGIS_VERSION}"
  else
    echo "FROM postgres:${PG_MAJOR}"
  fi
  echo "ARG PG_MAJOR=${PG_MAJOR}"
  if [ "${EN[vector]}" = 1 ]; then
    cat <<DF
RUN apt-get update \\
 && apt-get install -y --no-install-recommends \\
      postgresql-${PG_MAJOR}-pgvector ca-certificates wget \\
 && rm -rf /var/lib/apt/lists/*
DF
  fi
  if [ "${EN[api]}" = 1 ]; then
    if [ "${EN[vector]}" != 1 ]; then
      echo "RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates wget && rm -rf /var/lib/apt/lists/*"
    fi
    printf 'RUN set -eux; arch="$(dpkg --print-architecture)"; '
    printf 'url="https://github.com/supabase/pg_graphql/releases/download/v%s/pg_graphql-v%s-pg%s-${arch}-linux-gnu.deb"; ' \
      "$PG_GRAPHQL_VERSION" "$PG_GRAPHQL_VERSION" "$PG_MAJOR"
    printf 'wget -q -O /tmp/pg_graphql.deb "$url"; apt-get update; apt-get install -y --no-install-recommends /tmp/pg_graphql.deb; rm -f /tmp/pg_graphql.deb; rm -rf /var/lib/apt/lists/*\n'
  fi
  echo "COPY init/ /docker-entrypoint-initdb.d/"
} > build/Dockerfile

# --- 01-extensions.sql ---
{
  echo "-- generated by setup.sh; do not edit"
  [ "${EN[search]}" = 1 ] && echo "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
  [ "${EN[vector]}" = 1 ] && echo "CREATE EXTENSION IF NOT EXISTS vector;"
  [ "${EN[gis]}" = 1 ]    && echo "CREATE EXTENSION IF NOT EXISTS postgis;"
  [ "${EN[api]}" = 1 ]    && echo "CREATE EXTENSION IF NOT EXISTS pg_graphql;"
  true
} > build/init/01-extensions.sql

# --- 02-schema.sql (canonical order; api contributes no schema) ---
SEED="$(jq -r 'if .seed_demo_data == null then "true" else (.seed_demo_data | tostring) end' "$CONFIG")"
SCHEMA_ORDER=(document_store job_queue search vector gis timeseries dashboards auth)
{
  echo "-- generated by setup.sh; do not edit"
  for c in "${SCHEMA_ORDER[@]}"; do
    [ "${EN[$c]}" = 1 ] || continue
    cat "init/capabilities/$c.schema.sql"
    echo
    if [ "$SEED" = "true" ] && [ -f "init/capabilities/$c.seed.sql" ]; then
      cat "init/capabilities/$c.seed.sql"
      echo
    fi
  done
} > build/init/02-schema.sql

if [ "${EN[api]}" = 1 ]; then
  # --- 00-roles.sh ---
  cat > build/init/00-roles.sh <<'ROLES'
#!/bin/bash
set -euo pipefail
: "${AUTHENTICATOR_PASSWORD:?AUTHENTICATOR_PASSWORD must be set}"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
     --set authpw="$AUTHENTICATOR_PASSWORD" <<-'EOSQL'
    CREATE ROLE anon NOLOGIN;
    CREATE ROLE authenticated NOLOGIN;
    CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD :'authpw';
    GRANT anon, authenticated TO authenticator;
EOSQL
ROLES
  chmod +x build/init/00-roles.sh

  # --- 03-api-grants.sql (read tables scoped to enabled caps) ---
  declare -A READ_TABLE=(
    [document_store]=products [job_queue]=jobs [search]=articles
    [vector]=documents [gis]=places [timeseries]=events [dashboards]=event_daily
  )
  read_tables=""
  for c in document_store job_queue search vector gis timeseries dashboards; do
    [ "${EN[$c]}" = 1 ] && read_tables="${read_tables:+$read_tables, }${READ_TABLE[$c]}"
  done
  {
    echo "-- generated by setup.sh; do not edit"
    echo "GRANT USAGE ON SCHEMA public TO anon, authenticated;"
    if [ -n "$read_tables" ]; then echo "GRANT SELECT ON $read_tables TO anon, authenticated;"; fi
    if [ "${EN[auth]}" = 1 ]; then echo "GRANT SELECT, INSERT, UPDATE, DELETE ON notes TO authenticated;"; fi
    echo "GRANT USAGE ON SCHEMA graphql TO anon, authenticated;"
    echo "GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA graphql TO anon, authenticated;"
    echo "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO anon;"
  } > build/init/03-api-grants.sql
fi

# --- secrets: from config or generated ---
rand_secret() { openssl rand -hex 24; }
PG_USER="$(jq -r '.postgres.user // "postgres"' "$CONFIG")"
PG_DB="$(jq -r '.postgres.db // "app"' "$CONFIG")"
PG_PW="$(jq -r '.postgres.password // ""' "$CONFIG")"; [ -n "$PG_PW" ] || { PG_PW="$(rand_secret)"; GEN_PG=1; }

{
  echo "POSTGRES_USER=$PG_USER"
  echo "POSTGRES_PASSWORD=$PG_PW"
  echo "POSTGRES_DB=$PG_DB"
  if [ "${EN[api]}" = 1 ]; then
    AUTH_PW="$(jq -r '.api.authenticator_password // ""' "$CONFIG")"; [ -n "$AUTH_PW" ] || { AUTH_PW="$(openssl rand -hex 16)"; GEN_AUTH=1; }
    JWT="$(jq -r '.api.jwt_secret // ""' "$CONFIG")"; [ -n "$JWT" ] || { JWT="$(rand_secret)$(rand_secret)"; GEN_JWT=1; }
    echo "AUTHENTICATOR_PASSWORD=$AUTH_PW"
    echo "JWT_SECRET=$JWT"
  fi
} > build/.env
chmod 600 build/.env

PUBLISH_EXT="$(jq -r 'if .postgres.publish_externally == true then 1 else 0 end' "$CONFIG")"
if [ "$PUBLISH_EXT" = 1 ]; then BIND_PREFIX=""; else BIND_PREFIX="127.0.0.1:"; fi

# --- docker-compose.yml ---
{
  echo "services:"
  echo "  db:"
  echo "    build: ."
  echo "    image: postgres-everything:generated"
  echo "    restart: unless-stopped"
  echo "    environment:"
  echo "      POSTGRES_USER: \${POSTGRES_USER}"
  echo "      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}"
  echo "      POSTGRES_DB: \${POSTGRES_DB}"
  [ "${EN[api]}" = 1 ] && echo "      AUTHENTICATOR_PASSWORD: \${AUTHENTICATOR_PASSWORD}"
  echo "    ports:"
  echo "      - \"${BIND_PREFIX}5432:5432\""
  echo "    volumes:"
  echo "      - pgdata:/var/lib/postgresql/data"
  echo "    healthcheck:"
  echo "      test: [\"CMD-SHELL\", \"pg_isready -U \$\${POSTGRES_USER} -d \$\${POSTGRES_DB}\"]"
  echo "      interval: 5s"
  echo "      timeout: 5s"
  echo "      retries: 12"
  if [ "${EN[api]}" = 1 ]; then
    echo "  postgrest:"
    echo "    image: postgrest/postgrest:v12.2.3"
    echo "    restart: unless-stopped"
    echo "    environment:"
    echo "      PGRST_DB_URI: postgres://authenticator:\${AUTHENTICATOR_PASSWORD}@db:5432/\${POSTGRES_DB}"
    echo "      PGRST_DB_SCHEMAS: public"
    echo "      PGRST_DB_ANON_ROLE: anon"
    echo "      PGRST_JWT_SECRET: \${JWT_SECRET}"
    echo "    ports:"
    echo "      - \"${BIND_PREFIX}3000:3000\""
    echo "    depends_on:"
    echo "      db:"
    echo "        condition: service_healthy"
  fi
  echo "volumes:"
  echo "  pgdata:"
} > build/docker-compose.yml

# --- report generated secrets once (values stay in build/.env only) ---
if [ "${GEN_PG:-0}" = 1 ] || [ "${GEN_AUTH:-0}" = 1 ] || [ "${GEN_JWT:-0}" = 1 ]; then
  echo "Secrets were generated and written to build/.env (mode 0600). Keep that file safe and do not commit it."
fi

if [ "$DRY_RUN" -eq 1 ]; then
  echo "dry-run: build/ generated, not starting Docker"
  exit 0
fi

echo "starting stack..."
docker compose --env-file build/.env -f build/docker-compose.yml up --build
