-- generated by postgres4all; do not edit
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT USAGE, CREATE ON SCHEMA public TO api_owner;
GRANT SELECT ON products TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON products TO api_owner;
GRANT SELECT, INSERT, UPDATE, DELETE ON notes TO authenticated;
