-- generated by postgres4all; do not edit
-- document_store: MongoDB -> jsonb + GIN index
CREATE TABLE products (
    id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name       text  NOT NULL,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX products_attrs_gin ON products USING gin (attributes jsonb_path_ops);

INSERT INTO products (name, attributes) VALUES
    ('Mechanical Keyboard', '{"brand":"Keychron","switch":"brown","wireless":true,"tags":["typing","gaming"]}'),
    ('USB-C Hub',           '{"brand":"Anker","ports":7,"wireless":false}');

-- job_queue: Redis/RabbitMQ -> FOR UPDATE SKIP LOCKED
CREATE TABLE jobs (
    id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    payload    jsonb       NOT NULL,
    status     text        NOT NULL DEFAULT 'pending',
    locked_at  timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX jobs_pending_idx ON jobs (created_at) WHERE status = 'pending';

CREATE OR REPLACE FUNCTION dequeue_job()
RETURNS jobs
LANGUAGE sql AS $$
    UPDATE jobs
       SET status = 'processing', locked_at = now()
     WHERE id = (
         SELECT id FROM jobs
          WHERE status = 'pending'
          ORDER BY created_at
          FOR UPDATE SKIP LOCKED
          LIMIT 1
     )
    RETURNING *;
$$;

INSERT INTO jobs (payload)
SELECT jsonb_build_object('n', g) FROM generate_series(1, 10) AS g;

-- search: Elasticsearch -> tsvector + pg_trgm
CREATE TABLE articles (
    id    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    body  text NOT NULL,
    tsv   tsvector GENERATED ALWAYS AS
              (to_tsvector('english', title || ' ' || body)) STORED
);
CREATE INDEX articles_tsv_idx        ON articles USING gin (tsv);
CREATE INDEX articles_title_trgm_idx ON articles USING gin (title gin_trgm_ops);

INSERT INTO articles (title, body) VALUES
    ('Running Postgres in production', 'Tips for scaling and running your database under load.'),
    ('A guide to full text search',    'Using tsvector and tsquery effectively in Postgres.');

-- vector: Pinecone -> pgvector + HNSW
CREATE TABLE documents (
    id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner_id  bigint  NOT NULL DEFAULT 1,
    content   text    NOT NULL,
    embedding vector(3) NOT NULL
);
CREATE INDEX documents_embedding_hnsw
    ON documents USING hnsw (embedding vector_cosine_ops);

INSERT INTO documents (owner_id, content, embedding) VALUES
    (1, 'cat', '[0.10,0.20,0.30]'),
    (1, 'dog', '[0.12,0.19,0.31]'),
    (2, 'car', '[0.90,0.10,0.00]');

-- gis: PostGIS + GiST
CREATE TABLE places (
    id   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    geom geometry(Point, 4326) NOT NULL
);
CREATE INDEX places_geom_gist ON places USING gist (geom);

INSERT INTO places (name, geom) VALUES
    ('Cafe A', ST_SetSRID(ST_MakePoint(-122.4194, 37.7749), 4326)),
    ('Cafe B', ST_SetSRID(ST_MakePoint(-122.4084, 37.7849), 4326));

-- timeseries: declarative partitioning + BRIN
CREATE TABLE events (
    occurred_at timestamptz NOT NULL,
    kind        text        NOT NULL,
    data        jsonb       NOT NULL DEFAULT '{}'::jsonb
) PARTITION BY RANGE (occurred_at);

CREATE TABLE events_2026_06 PARTITION OF events
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE events_2026_07 PARTITION OF events
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');

CREATE INDEX events_brin ON events USING brin (occurred_at);

INSERT INTO events (occurred_at, kind)
SELECT TIMESTAMPTZ '2026-06-01' + (g || ' minutes')::interval, 'click'
FROM generate_series(1, 1000) AS g;

-- dashboards: Snowflake -> materialized view (requires timeseries' events table)
CREATE MATERIALIZED VIEW event_daily AS
    SELECT date_trunc('day', occurred_at) AS day,
           kind,
           count(*) AS n
    FROM events
    GROUP BY 1, 2
    WITH DATA;
CREATE UNIQUE INDEX event_daily_pk ON event_daily (day, kind);

-- auth: row-level security (exposed via PostgREST role switch)
CREATE TABLE notes (
    id    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner text NOT NULL DEFAULT current_setting('request.jwt.claims', true)::json ->> 'sub',
    body  text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY notes_isolation ON notes
    USING      (owner = current_setting('request.jwt.claims', true)::json ->> 'sub')
    WITH CHECK (owner = current_setting('request.jwt.claims', true)::json ->> 'sub');

