-- generated by postgres4all; do not edit
CREATE SCHEMA IF NOT EXISTS p4a_meta;
CREATE TABLE IF NOT EXISTS p4a_meta.capabilities (
    cap        text PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO p4a_meta.capabilities (cap) VALUES ('document_store') ON CONFLICT (cap) DO NOTHING;
INSERT INTO p4a_meta.capabilities (cap) VALUES ('job_queue') ON CONFLICT (cap) DO NOTHING;
INSERT INTO p4a_meta.capabilities (cap) VALUES ('search') ON CONFLICT (cap) DO NOTHING;
INSERT INTO p4a_meta.capabilities (cap) VALUES ('vector') ON CONFLICT (cap) DO NOTHING;
INSERT INTO p4a_meta.capabilities (cap) VALUES ('gis') ON CONFLICT (cap) DO NOTHING;
INSERT INTO p4a_meta.capabilities (cap) VALUES ('timeseries') ON CONFLICT (cap) DO NOTHING;
INSERT INTO p4a_meta.capabilities (cap) VALUES ('dashboards') ON CONFLICT (cap) DO NOTHING;
INSERT INTO p4a_meta.capabilities (cap) VALUES ('api') ON CONFLICT (cap) DO NOTHING;
INSERT INTO p4a_meta.capabilities (cap) VALUES ('auth') ON CONFLICT (cap) DO NOTHING;
