{{- if .GIS}}FROM postgis/postgis:{{.PGMajor}}-{{.PostGISVersion}}
{{- else}}FROM postgres:{{.PGMajor}}
{{- end}}
ARG PG_MAJOR={{.PGMajor}}
{{- if .Vector}}
RUN apt-get update && apt-get install -y --no-install-recommends postgresql-{{.PGMajor}}-pgvector ca-certificates wget && rm -rf /var/lib/apt/lists/*
{{- end}}
{{- if .LangPkgs}}
RUN apt-get update && apt-get install -y --no-install-recommends{{range .LangPkgs}} {{.}}{{end}} && rm -rf /var/lib/apt/lists/*
{{- end}}
COPY init/ /docker-entrypoint-initdb.d/
