-- generated by postgres4all; do not edit
-- gis: PostGIS + GiST
CREATE TABLE places (
    id   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    geom geometry(Point, 4326) NOT NULL
);
CREATE INDEX places_geom_gist ON places USING gist (geom);

INSERT INTO places (name, geom) VALUES
    ('Cafe A', ST_SetSRID(ST_MakePoint(-122.4194, 37.7749), 4326)),
    ('Cafe B', ST_SetSRID(ST_MakePoint(-122.4084, 37.7849), 4326));

