package generate

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/Havoc24k/postgres4all/internal/config"
	"github.com/Havoc24k/postgres4all/internal/secrets"
)

// Pinned constants.
const (
	PGMajor          = "17"
	PostGISVersion   = "3.5"
	PgGraphQLVersion = "1.5.11"
	PostgRESTImage   = "postgrest/postgrest:v12.2.3"
	GeneratedImage   = "postgres4all:generated"
)

const header = "-- generated by postgres4all; do not edit\n"

// ExtensionMap maps capability name to Postgres extension name.
var ExtensionMap = map[string]string{
	"search": "pg_trgm",
	"vector": "vector",
	"gis":    "postgis",
	"api":    "pg_graphql",
}

// ReadTableMap maps capability name to its primary read table.
var ReadTableMap = map[string]string{
	"document_store": "products",
	"job_queue":      "jobs",
	"search":         "articles",
	"vector":         "documents",
	"gis":            "places",
	"timeseries":     "events",
	"dashboards":     "event_daily",
}

// ReadCapabilitySQL returns an embedded capability fragment, e.g. ReadCapabilitySQL("document_store.schema.sql").
func ReadCapabilitySQL(name string) ([]byte, error) {
	return capabilitiesFS.ReadFile("capabilities/" + name)
}

// schemaOrder is the capability order for schema assembly: config.Order without "api" (api owns no schema).
var schemaOrder = func() []string {
	out := make([]string, 0, len(config.Order))
	for _, c := range config.Order {
		if c != "api" {
			out = append(out, c)
		}
	}
	return out
}()

// rolesShScript is the exact content of 00-roles.sh (shell script, no Go interpolation).
const rolesShScript = `#!/bin/bash
set -euo pipefail
: "${AUTHENTICATOR_PASSWORD:?AUTHENTICATOR_PASSWORD must be set}"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
     --set authpw="$AUTHENTICATOR_PASSWORD" <<-'EOSQL'
    CREATE ROLE anon NOLOGIN;
    CREATE ROLE authenticated NOLOGIN;
    CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD :'authpw';
    CREATE ROLE api_owner NOLOGIN NOINHERIT;
    GRANT anon, authenticated TO authenticator;
EOSQL
`

// Generate writes the build output directory from the given config.
// It deletes only its own artifacts (Dockerfile, docker-compose.yml, .env, init/)
// before regenerating — never removes the entire outDir.
func Generate(c *config.Config, outDir string) error {
	// Capture existing secrets before we delete .env, so regeneration (e.g. via `update`) keeps them.
	preserved := readEnv(filepath.Join(outDir, ".env"))

	// Step 1: Delete owned artifacts, then recreate init/.
	for _, name := range []string{"Dockerfile", "docker-compose.yml", ".env"} {
		_ = os.Remove(filepath.Join(outDir, name))
	}
	_ = os.RemoveAll(filepath.Join(outDir, "init"))
	if err := os.MkdirAll(filepath.Join(outDir, "init"), 0o755); err != nil {
		return fmt.Errorf("creating init dir: %w", err)
	}

	// Step 2: Dockerfile.
	if err := renderDockerfile(c, outDir); err != nil {
		return err
	}

	// Step 3: 01-extensions.sql.
	if err := writeExtensions(c, outDir); err != nil {
		return err
	}

	// Step 4: 02-schema.sql.
	if err := writeSchema(c, outDir); err != nil {
		return err
	}

	// Step 5: 04-meta.sql.
	if err := writeMeta(c, outDir); err != nil {
		return err
	}

	// Step 6: API files (00-roles.sh + 03-api-grants.sql).
	if c.Enabled("api") {
		if err := writeRoles(outDir); err != nil {
			return err
		}
		if err := writeAPIGrants(c, outDir); err != nil {
			return err
		}
	}

	// Step 7: Resolve secrets and write .env.
	if err := writeEnv(c, outDir, preserved); err != nil {
		return err
	}

	// Step 8: docker-compose.yml.
	if err := writeCompose(c, outDir); err != nil {
		return err
	}

	return nil
}

// renderDockerfile renders Dockerfile.tmpl into outDir/Dockerfile.
func renderDockerfile(c *config.Config, outDir string) error {
	type dockerfileModel struct {
		GIS            bool
		Vector         bool
		API            bool
		PGMajor        string
		PostGISVersion string
		PgGraphQL      string
		LangPkgs       []string
	}

	var langPkgs []string
	if c.Languages.PLPerl {
		langPkgs = append(langPkgs, "postgresql-plperl-"+PGMajor)
	}
	if c.Languages.PLPython {
		langPkgs = append(langPkgs, "postgresql-plpython3-"+PGMajor)
	}

	m := dockerfileModel{
		GIS:            c.Enabled("gis"),
		Vector:         c.Enabled("vector"),
		API:            c.Enabled("api"),
		PGMajor:        PGMajor,
		PostGISVersion: PostGISVersion,
		PgGraphQL:      PgGraphQLVersion,
		LangPkgs:       langPkgs,
	}

	tmpl, err := template.ParseFS(templatesFS, "templates/Dockerfile.tmpl")
	if err != nil {
		return fmt.Errorf("parsing Dockerfile.tmpl: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, m); err != nil {
		return fmt.Errorf("executing Dockerfile.tmpl: %w", err)
	}

	return os.WriteFile(filepath.Join(outDir, "Dockerfile"), buf.Bytes(), 0o644)
}

// writeExtensions writes init/01-extensions.sql.
func writeExtensions(c *config.Config, outDir string) error {
	var sb strings.Builder
	sb.WriteString(header)

	// Extensions in capability order: search, vector, gis, api; then languages.
	extCaps := []string{"search", "vector", "gis", "api"}
	for _, cap := range extCaps {
		if c.Enabled(cap) {
			ext := ExtensionMap[cap]
			sb.WriteString("CREATE EXTENSION IF NOT EXISTS " + ext + ";\n")
		}
	}
	if c.Languages.PLPerl {
		sb.WriteString("CREATE EXTENSION IF NOT EXISTS plperl;\n")
	}
	if c.Languages.PLPython {
		sb.WriteString("CREATE EXTENSION IF NOT EXISTS plpython3u;\n")
	}

	return os.WriteFile(filepath.Join(outDir, "init", "01-extensions.sql"), []byte(sb.String()), 0o644)
}

// writeSchema writes init/02-schema.sql.
func writeSchema(c *config.Config, outDir string) error {
	var sb strings.Builder
	sb.WriteString(header)

	for _, cap := range schemaOrder {
		if !c.Enabled(cap) {
			continue
		}
		// Write schema fragment.
		schemaBytes, err := capabilitiesFS.ReadFile("capabilities/" + cap + ".schema.sql")
		if err != nil {
			return fmt.Errorf("reading capabilities/%s.schema.sql: %w", cap, err)
		}
		sb.Write(schemaBytes)
		sb.WriteString("\n")

		// Write seed fragment if seeding is enabled and seed exists.
		if c.Seed() {
			seedPath := "capabilities/" + cap + ".seed.sql"
			seedBytes, err := capabilitiesFS.ReadFile(seedPath)
			if err == nil {
				sb.Write(seedBytes)
				sb.WriteString("\n")
			}
			// If error (file not found), skip silently.
		}
	}

	return os.WriteFile(filepath.Join(outDir, "init", "02-schema.sql"), []byte(sb.String()), 0o644)
}

// writeMeta writes init/04-meta.sql.
func writeMeta(c *config.Config, outDir string) error {
	var sb strings.Builder
	sb.WriteString(header)
	sb.WriteString("CREATE SCHEMA IF NOT EXISTS p4a_meta;\n")
	sb.WriteString("CREATE TABLE IF NOT EXISTS p4a_meta.capabilities (\n")
	sb.WriteString("    cap        text PRIMARY KEY,\n")
	sb.WriteString("    applied_at timestamptz NOT NULL DEFAULT now()\n")
	sb.WriteString(");\n")

	// Insert all enabled capabilities in canonical order (api included).
	for _, cap := range config.Order {
		if c.Enabled(cap) {
			sb.WriteString(fmt.Sprintf("INSERT INTO p4a_meta.capabilities (cap) VALUES ('%s') ON CONFLICT (cap) DO NOTHING;\n", cap))
		}
	}

	return os.WriteFile(filepath.Join(outDir, "init", "04-meta.sql"), []byte(sb.String()), 0o644)
}

// writeRoles writes init/00-roles.sh (mode 0o755).
func writeRoles(outDir string) error {
	path := filepath.Join(outDir, "init", "00-roles.sh")
	if err := os.WriteFile(path, []byte(rolesShScript), 0o755); err != nil {
		return fmt.Errorf("writing 00-roles.sh: %w", err)
	}
	return nil
}

// writeAPIGrants writes init/03-api-grants.sql.
func writeAPIGrants(c *config.Config, outDir string) error {
	var sb strings.Builder
	sb.WriteString(header)
	sb.WriteString("GRANT USAGE ON SCHEMA public TO anon, authenticated;\n")
	// api_owner is the non-superuser role that owns SECURITY DEFINER RPCs (apply-functions
	// creates them via SET ROLE api_owner). It needs USAGE+CREATE on the schema to own
	// functions, and DML on the app tables so those functions can do their privileged work.
	// It is NOT a PostgREST switch-target (authenticator cannot SET ROLE to it), so its
	// table access is never directly reachable by an API caller.
	sb.WriteString("GRANT USAGE, CREATE ON SCHEMA public TO api_owner;\n")

	// Build read-tables list in canonical order (excluding api and auth, which have no read table).
	var tables []string
	for _, cap := range config.Order {
		if cap == "api" || cap == "auth" {
			continue
		}
		if c.Enabled(cap) {
			if tbl, ok := ReadTableMap[cap]; ok {
				tables = append(tables, tbl)
			}
		}
	}
	if len(tables) > 0 {
		sb.WriteString("GRANT SELECT ON " + strings.Join(tables, ", ") + " TO anon, authenticated;\n")
		sb.WriteString("GRANT SELECT, INSERT, UPDATE, DELETE ON " + strings.Join(tables, ", ") + " TO api_owner;\n")
	}

	if c.Enabled("auth") {
		sb.WriteString("GRANT SELECT, INSERT, UPDATE, DELETE ON notes TO authenticated;\n")
	}

	sb.WriteString("GRANT USAGE ON SCHEMA graphql TO anon, authenticated;\n")
	sb.WriteString("GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA graphql TO anon, authenticated;\n")
	if c.Security.AnonFutureTables {
		sb.WriteString("ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO anon;\n")
	}

	return os.WriteFile(filepath.Join(outDir, "init", "03-api-grants.sql"), []byte(sb.String()), 0o644)
}

// readEnv parses KEY=value lines from an .env file; returns an empty map if it's absent.
func readEnv(path string) map[string]string {
	m := map[string]string{}
	b, err := os.ReadFile(path)
	if err != nil {
		return m
	}
	for _, line := range strings.Split(string(b), "\n") {
		if k, v, ok := strings.Cut(line, "="); ok {
			m[k] = strings.TrimRight(v, "\r")
		}
	}
	return m
}

// writeEnv resolves secrets and writes .env (mode 0o600).
func writeEnv(c *config.Config, outDir string, preserved map[string]string) error {
	// Postgres password: config value > preserved (existing .env) > freshly generated.
	pgPass := c.Postgres.Password
	if pgPass == "" {
		pgPass = preserved["POSTGRES_PASSWORD"]
	}
	if pgPass == "" {
		var err error
		pgPass, err = secrets.Hex(24)
		if err != nil {
			return fmt.Errorf("generating postgres password: %w", err)
		}
	}

	// API secrets are always auto-generated (no config knob); preserved across regeneration.
	var authPw, jwt string
	if c.Enabled("api") {
		authPw = preserved["AUTHENTICATOR_PASSWORD"]
		if authPw == "" {
			var err error
			authPw, err = secrets.Hex(16)
			if err != nil {
				return fmt.Errorf("generating authenticator password: %w", err)
			}
		}
		jwt = preserved["JWT_SECRET"]
		if jwt == "" {
			var err error
			jwt, err = secrets.Hex(48)
			if err != nil {
				return fmt.Errorf("generating jwt secret: %w", err)
			}
		}
	}

	type envModel struct {
		User             string
		Password         string
		DB               string
		API              bool
		AuthPw           string
		JWT              string
		DBService        string
		PostgRESTService string
	}

	m := envModel{
		User:             c.Postgres.User,
		Password:         pgPass,
		DB:               c.Postgres.DB,
		API:              c.Enabled("api"),
		AuthPw:           authPw,
		JWT:              jwt,
		DBService:        c.Compose.Services["db"],        // empty unless overridden
		PostgRESTService: c.Compose.Services["postgrest"], // empty unless overridden
	}

	tmpl, err := template.ParseFS(templatesFS, "templates/env.tmpl")
	if err != nil {
		return fmt.Errorf("parsing env.tmpl: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, m); err != nil {
		return fmt.Errorf("executing env.tmpl: %w", err)
	}

	path := filepath.Join(outDir, ".env")
	if err := os.WriteFile(path, buf.Bytes(), 0o600); err != nil {
		return fmt.Errorf("writing .env: %w", err)
	}
	return nil
}

// writeCompose renders docker-compose.yml.tmpl into outDir/docker-compose.yml.
func writeCompose(c *config.Config, outDir string) error {
	bind := "127.0.0.1:"
	if c.Postgres.PublishExternally {
		bind = ""
	}

	type composeModel struct {
		Image            string
		PostgRESTImage   string
		Bind             string
		API              bool
		Name             string
		DBService        string
		PostgRESTService string
		DBPort           int
		PostgRESTPort    int
		JWTAud           string
	}

	m := composeModel{
		Image:            GeneratedImage,
		PostgRESTImage:   PostgRESTImage,
		Bind:             bind,
		API:              c.Enabled("api"),
		Name:             c.ProjectName(),
		DBService:        c.DBService(),
		PostgRESTService: c.PostgRESTService(),
		DBPort:           c.DBPort(),
		PostgRESTPort:    c.PostgRESTPort(),
		JWTAud:           c.Security.JWTAudience,
	}

	tmpl, err := template.ParseFS(templatesFS, "templates/docker-compose.yml.tmpl")
	if err != nil {
		return fmt.Errorf("parsing docker-compose.yml.tmpl: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, m); err != nil {
		return fmt.Errorf("executing docker-compose.yml.tmpl: %w", err)
	}

	return os.WriteFile(filepath.Join(outDir, "docker-compose.yml"), buf.Bytes(), 0o644)
}
